### ISSUE TITLE
Error: Cannot find module 'rollup/bin/rollup'

### ISSUE THREAD

**Issue by darkpoem** [nagix/chartjs-plugin-colorschemes#24]
Trying to build the project, got an error after running gulp build, what am I doing wrong?

>  node --version
> v14.15.5
>  npm --version
> 7.5.4
>  gulp --version
> CLI version: 2.3.0
> Local version: 4.0.2

Steps to reproduce
> git clone https://github.com/nagix/chartjs-plugin-colorschemes
> cd chartjs-plugin-colorschemes
> npm install
> gulp build

```
isangjae@siin-iui-MacBookPro chartjs-plugin-colorschemes % gulp build
[14:26:46] Using gulpfile /Volumes/DK_DEV/project/chartjs-plugin-colorschemes/gulpfile.js
[14:26:46] Starting 'build'...
[14:26:46] 'build' errored after 3.24 ms
[14:26:46] Error: Cannot find module 'rollup/bin/rollup'
Require stack:
- /Volumes/DK_DEV/project/chartjs-plugin-colorschemes/gulpfile.js
- /usr/local/lib/node_modules/gulp/node_modules/gulp-cli/lib/shared/require-or-import.js
- /usr/local/lib/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js
/* global Promise */
- /usr/local/lib/node_modules/gulp/node_modules/gulp-cli/index.js
- /usr/local/lib/node_modules/gulp/bin/gulp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at /Volumes/DK_DEV/project/chartjs-plugin-colorschemes/gulpfile.js:24:21
    at new Promise (<anonymous>)
    at run (/Volumes/DK_DEV/project/chartjs-plugin-colorschemes/gulpfile.js:22:9)
    at /Volumes/DK_DEV/project/chartjs-plugin-colorschemes/gulpfile.js:40:9
    at build (/Volumes/DK_DEV/project/chartjs-plugin-colorschemes/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:413:15)
    at runBound (domain.js:424:12)
    at asyncRunner (/Volumes/DK_DEV/project/chartjs-plugin-colorschemes/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**Comment by MartijnVerkleij** [comment]
I propose a hotfix in #26 (https://github.com/nagix/chartjs-plugin-colorschemes/pull/26/commits/35f10ba9999253f57a4af36d9f998937a65d5d3d)
